# mysql.yml
---

# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Configure mysql
  template: src="my.j2" dest="{{ mysql_config_file }}"
            backup=yes
            owner=root
            group=root
            mode=0644
  notify: restart mysql

- name: Start Mysql
  service: name={{ mysql_daemon }} state=started enabled=yes

- include: hardening-mysql.yml
  when: mysql_root_password is defined

